#!/bin/bash

cd wwucrawler/
./run &> ../crawler.log &
if [ $? -eq 0 ]; then
    echo 'Crawler running! Do `tail -f crawler.log` to see its progress.'

    cd ../committee_scraper/
    ./run &> ../summarizer.log &
    if [ $? -eq 0 ]; then
        echo 'Summarizer running! Do `tail -f summarizer.log` to see its progress.'

        cd ../frontend/
        npm run dev &> ../frontend.log &
        if [ $? -eq 0 ]; then
            echo 'Frontend running! Do `tail -f frontend.log` to see its output.'

            cd ../flaskapp/
            .env/bin/python app.py
        else
            echo 'Failed to start frontend. Giving up...'
        fi
    else
        echo 'Failed to start summarizer. Giving up...'
    fi
else
    echo 'Failed to start crawler. Giving up...'
fi
