#!/bin/bash

cd wwucrawler/
if [ ! -d .env ]; then
	python3 -m venv .env
fi

.env/bin/pip install -r requirements.txt

cd ../flaskapp/
if [ ! -d .env ]; then
	python3 -m venv .env
fi;

.env/bin/pip install -r requirements.txt

cd ../committee_scraper/
if [ ! -d .env ]; then
	python3 -m venv .env
fi;

.env/bin/pip install -r requirements.txt

cd ../frontend/
npm install
