import os
from flask import Flask, send_file, send_from_directory, redirect, url_for, jsonify
from sqlite3 import connect, Cursor
from typing import Any

# Getting the app started
app = Flask(__name__)


VITE_OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "../frontend/dist/")


# Display index.html generated by Vite
@app.route("/")
def index():
    if not os.path.isdir(VITE_OUTPUT_DIR):
        return redirect(url_for("not_found"))
    else:
        return send_file(
            os.path.join(os.path.dirname(__file__), "../frontend/dist/index.html")
        )


# Search for JSON data.
@app.route("/data/<path:subpath>")
def data(subpath):
    if not os.path.isdir("data/"):
        return redirect(url_for("not_found"))
    else:
        return send_from_directory("data/", subpath)


@app.route("/pages.json")
def pages_list():
    table = []
    if os.path.isfile("../pages.db"):
        with connect("../pages.db") as db_con:
            table = full_pages_table(db_con.cursor())

    return jsonify(table)


# Fetch other pages generated by Vite
@app.route("/<path:subpath>")
def dist(subpath):
    if not os.path.isdir(VITE_OUTPUT_DIR):
        return redirect(url_for("not_found"))
    else:
        return send_file(
            os.path.join(os.path.dirname(__file__), "../frontend/dist/", subpath)
        )


def full_pages_table(cur: Cursor) -> list[dict[str, Any]]:
    cur.execute(
        "SELECT url, title, score, summary_before, summary_keyword, summary_after FROM pages WHERE score > 0 ORDER BY score DESC"
    )
    rows = cur.fetchall()

    results = []
    for url, title, score, summary_before, summary_keyword, summary_after in rows:
        results.append(
            {
                "url": url,
                "title": title if title is not None else url,
                "score": score,
                "summary_before": summary_before,
                "summary_keyword": summary_keyword,
                "summary_after": summary_after,
            }
        )

    return results


if __name__ == "__main__":
    app.run(debug=True)
