#!/bin/bash

OUT_FILE=output.txt
DEPTH=2
KEYWORDS=("Committee" "committee" "associated students" "ASWWU" "AS" "board" "at-large" "student ambassador")

rm -f ../pages.db
.env/bin/python crawler -o"$OUT_FILE" -d"$DEPTH" $@ "${KEYWORDS[@]}" &&
	echo "Search of wwu.edu for keywords [${KEYWORDS[@]}] (depth $DEPTH) complete!" &&
	echo "Check $OUT_FILE for search results."
