#!/bin/bash

OUT_FILE=output.txt
DEPTH=1
KEYWORDS=("no" "more" "computer" "science")

python3 crawler -o"$OUT_FILE" -d"$DEPTH" "${KEYWORDS[@]}" &&
	echo "Search of wwu.edu for keywords [${KEYWORDS[@]}] (depth $DEPTH) complete!" &&
	echo "Check $OUT_FILE for search results."
